name: MacOS Tmate

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: SSH Keepalive Hack
      run: |
        brew install fish neofetch
        fish -C "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"
        fish -C "fisher install adamchristiansen/vertical-fish"
        echo /usr/local/bin/fish | sudo tee -a /etc/shells
        mkdir -p ~/.ssh
        cat << EOF > ~/.ssh/config
        Host *
            ServerAliveInterval 60
            StrictHostKeyChecking no
        Host github.com
            User git
            Port 22
            Hostname github.com
            TCPKeepAlive yes
            IdentitiesOnly yes
        EOF
    - name: Connecton to tmate
      continue-on-error: true
      timeout-minutes: 350
      uses: P3TERX/ssh2actions@main
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
