name: Ubuntu Tmate

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: SSH Keepalive Hack
      run: |
        mkdir -p ~/.ssh
        cat << EOF > ~/.ssh/config
        Host *
            ServerAliveInterval 60
            StrictHostKeyChecking no
        Host github.com
            User git
            Port 22
            Hostname github.com
            TCPKeepAlive yes
            IdentitiesOnly yes
        EOF
    - name: Setting up shell
      run: |
        sudo apt install fish neofetch
        cd
        sed -i '1ifish' .bashrc
        sed -i '1ineofetch' .bashrc
    - name: Connecton to tmate
      continue-on-error: true
      timeout-minutes: 350
      uses: P3TERX/ssh2actions@main
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
